### ISSUE TITLE
[en] so_5::deregister_coop_on_exception & exception requirements

### ISSUE THREAD

**Issue by basiliscos** [eao197/so-5-5#24]
Hi,

It is setup to handle exceptions via `coop.set_exception_reaction(so_5::deregister_coop_on_exception);`

When an child agent throws an arbitrary exception, not derived from `std::except`, it just terminates:

```cpp
...
throw ("boom");
```

```    
terminate called after throwing an instance of 'char const*'
[1]    18965 abort      ./syncspirit --log_level debug --config_file ../syncspirit.conf
```

However, when std::exception is thrown:

```cpp
...
throw std::runtime_error("boom");
```

Then it is catch and behaves correctly

```
SObjectizer event exception caught: boom; cooperation: 'logger'
[2019-03-09 11:47:51.577 TID:140664060745472] Cooperation 'logger' will be deregistered due to unhandled exception 'boom' (/home/b/development/cpp/sync-spirit/lib/so-5-5/dev/so_5/rt/impl/process_unhandled_exception.cpp:189)
```

I think it is too strong assumption, that 3rd-party libraries will always throw something derived from `std::except`

PS. It is also terminates on `throw new std::runtime_error("boom")`. Of course, this is buggy/discouraged to throw `new` exception, but that's what I met in the others' code.

**Comment by eao197** [comment]
I think that throwing an exception that is not derived from `std::exception` is a very bad practice. If an application uses some library that does this then it is a task of the application to catch such exceptions and wrap them into something normal.

But I will take a look at SObjectizer's code. If handling of arbitrary exceptions requires just a couple of `catch(...)` then I will update SObjectizer.

**Comment by eao197** [comment]
You can try [SO-5.5.24.3](https://groups.google.com/d/msg/sobjectizer/HJ8RzoxOoS4/neQsrNt0AwAJ).

**Comment by basiliscos** [comment]
Thank you!
