### ISSUE TITLE
[en] how to integrate extenral loop in SO?

### ISSUE THREAD

**Issue by basiliscos** [eao197/so-5-5#25]
I'm not sure that I do the right integration of a loop. Basically I do:

```cpp
void my_actor::so_evt_start() {
    so_subscribe_self().event<message::wakeup>(&wx_actor::on_wakeup);
    timer = so_5::send_periodic<message::wakeup>(*this, 0ms, 10ms);
}

void my_actor:::on_wakeup() {
    auto has_events = external_loop->Pending();
    while(has_events) {
        external_loop->DispatchTimeout(10); // can be just non-blocking external_loop->DispatchTimeout(()
        has_events = external_loop->Pending();
    }
    timer = so_5::send_periodic<message::wakeup>(*this, 10ms, 0ms);
}
```

in other words, it blocks SO-dispatcher for 10ms to process events, and then does `10ms` pause, and repeats. 

I'm a bit worry, that on idle it still consumes a lot of CPU (14%). If the wake-up event is send every `100ms` there is no CPU consumption, but by the price of loosing some interactivity. 

May be there are some other ways? i.e. not guessing the values between 100ms and 10ms ? 

PS. The external loop I'm trying to integrate is wx-widget ( https://docs.wxwidgets.org/3.0/classwx_event_loop_base.html )

PPS. I'm aware, that it is possible to do that in "wx-widgets" specific way, i.e. launch an dedicated thread, and deliver events in framework-specific way ( i.e. https://wiki.wxwidgets.org/Inter-Thread_and_Inter-Process_communication ). But I'd like to use nice sobjectizer as messaging framework.

**Comment by eao197** [comment]
You can try to set up `simple_lock_factory` for SObjectizer's Environment: [some docs](https://sourceforge.net/p/sobjectizer/wiki/so-5.5.18%20Global%20lock_factories/). It can reduce CPU consumption.

**Comment by eao197** [comment]
I'll look at wxWidgets doc tomorrow, maybe there is some way to make message exchange between wx and SO without delays and sleeping.

**Comment by basiliscos** [comment]
The `simple_lock_factory` seems quite good start, as it consumes about 2% of CPU. Thanks!

**Comment by eao197** [comment]
What is the goal of integration of wx-loop into SObjectizer? Do you want to run SObjectizer's agents with wx-widgets on the same thread? Or something else?

**Comment by basiliscos** [comment]
Yeah, indeed, if running wx-loop will be running on it's own thread no such a problem occurs (I'd like avoid that, but it seems not easy to do).

**Comment by eao197** [comment]
I think there are two ways to allow SObjectizer's agents to shared working context with wx's widgets:

* a special dispatcher. This dispatcher will use wxCommandEvent objects for wrapping SObjectizer's execution demands. In that case, SObjectizer can be launched on a separate thread, but agents bound to that special dispatcher will work on the main GUI thread (where the main wx-loop is running);
* a special env-infrastructure (like [so5extra asio-based infrastructure](https://sourceforge.net/p/sobjectizer/wiki/so5extra%201.0%20Asio-based%20Non-Thread-Safe%20Environment%20Infrastructure/)). In that case all agents bound to the default dispatcher will work on the main GUI thread via wx-loop (wxCommandEvent will be used for that purpose).

Both approaches are rather complex, especially the second. But in v.5.6.0 (that is almost in beta-version stage now) the development of custom dispatcher will be much easier than in v.5.5.

**Comment by basiliscos** [comment]
Perfect! Thanks for details... Will look at `5.6.0` once it's out :)
