### ISSUE TITLE
[ru] Фильтры сообщений для реализации в v.5.5.5

### ISSUE THREAD

**Issue by eao197** [eao197/so-5-5#3]
Подробное описание на [SF.net](https://sourceforge.net/p/sobjectizer/discussion/550088/thread/4c7b05f6/). Обсуждать можно и здесь.

**Comment by DronMDF** [comment]
А весь мониторинг - это события одного типа?
Нельзя целенаправленно подписаться на определенную часть информации?

**Comment by eao197** [comment]
Сейчас да: сообщения одного типа (stats::messages::quantity) летят в один mbox. Внутри же каждое сообщение содержит свою специфическую информацию: например, количество зарегистрированных коопераций, количество привязанных к конкретному диспетчеру агентов, количество заявок в очереди.
Если делать возможность какого-то дробления, тогда сильно разрастается инфраструктура. Например, если заставить каждого диспетчера отправлять свою информацию в свой собственный mbox, то возникнут сложности со сбором информации от нескольких диспетчеров.
В будущем планируется добавлять новые типы информации (например, средние времена простоя заявок в очередях, среднее время обработки события агентом). Но я собирался это делать аналогично -- новый тип сообщения (скажем, stats::messages::avg_times), экземпляры которого отсылаются на тот же mbox.

**Comment by eao197** [comment]
Реализовано. Войдет в состав v.5.5.5.
Подробное описание [здесь](https://sourceforge.net/p/sobjectizer/wiki/so-5.5.5%20Message%20delivery%20filters/)
